/**
 * SwiftZone WiFi Hotspot Automation Server
 * ==========================================
 * Stack: Node.js + Express
 * Connects: M-Pesa Daraja API → MikroTik Router → Africa's Talking SMS
 * 
 * Flow:
 * 1. Customer picks bundle & pays via M-Pesa STK push
 * 2. Daraja sends payment callback to this server
 * 3. Server generates voucher on MikroTik router
 * 4. Server sends voucher code to customer via SMS
 * 5. Owner gets a WhatsApp/SMS notification
 */

const express = require('express');
const axios = require('axios');
const RouterOSAPI = require('node-routeros').RouterOSAPI;
const AfricasTalking = require('africastalking');
const crypto = require('crypto');
const cors = require('cors');
require('dotenv').config();

const app = express();
app.use(express.json());
app.use(cors());

// ─────────────────────────────────────────
// BUNDLE PLANS CONFIG
// Edit these to match your client's pricing
// ─────────────────────────────────────────
const BUNDLES = {
  '1hr':     { label: '1 Hour',   price: 10,  duration: '01:00:00', speed: '5M/5M'  },
  'daily':   { label: 'Daily',    price: 50,  duration: '1d 00:00:00', speed: '10M/10M' },
  'weekly':  { label: 'Weekly',   price: 250, duration: '7d 00:00:00', speed: '15M/15M' },
  'monthly': { label: 'Monthly',  price: 800, duration: '30d 00:00:00', speed: '20M/20M' },
};

// ─────────────────────────────────────────
// AFRICA'S TALKING SMS SETUP
// ─────────────────────────────────────────
const AT = AfricasTalking({
  apiKey: process.env.AT_API_KEY,
  username: process.env.AT_USERNAME,
});
const sms = AT.SMS;

// ─────────────────────────────────────────
// MPESA TOKEN HELPER
// ─────────────────────────────────────────
async function getMpesaToken() {
  const key = process.env.MPESA_CONSUMER_KEY;
  const secret = process.env.MPESA_CONSUMER_SECRET;
  const auth = Buffer.from(`${key}:${secret}`).toString('base64');

  const res = await axios.get(
    'https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials',
    { headers: { Authorization: `Basic ${auth}` } }
  );
  return res.data.access_token;
}

// ─────────────────────────────────────────
// GENERATE UNIQUE VOUCHER CODE
// Format: SW-XXXX (e.g. SW-K9P2)
// ─────────────────────────────────────────
function generateVoucherCode() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = 'SW-';
  for (let i = 0; i < 4; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

// ─────────────────────────────────────────
// MIKROTIK: CREATE HOTSPOT VOUCHER
// ─────────────────────────────────────────
async function createMikrotikVoucher(bundle, voucherCode) {
  const conn = new RouterOSAPI({
    host: process.env.MIKROTIK_HOST,
    user: process.env.MIKROTIK_USER,
    password: process.env.MIKROTIK_PASS,
    port: parseInt(process.env.MIKROTIK_PORT) || 8728,
  });

  await conn.connect();

  const plan = BUNDLES[bundle];

  // Add hotspot user (this IS the voucher)
  await conn.write('/ip/hotspot/user/add', [
    `=name=${voucherCode}`,
    `=password=${voucherCode}`,
    `=profile=${bundle}`,   // Must match a hotspot user profile on MikroTik
    `=limit-uptime=${plan.duration}`,
    `=comment=Auto-generated by SwiftZone | ${plan.label}`,
  ]);

  conn.close();
  return true;
}

// ─────────────────────────────────────────
// SEND SMS TO CUSTOMER
// ─────────────────────────────────────────
async function sendVoucherSMS(phone, voucherCode, bundle) {
  const plan = BUNDLES[bundle];

  // Format phone to international (+254...)
  let formatted = phone.replace(/\s/g, '');
  if (formatted.startsWith('0')) formatted = '+254' + formatted.slice(1);
  if (formatted.startsWith('254')) formatted = '+' + formatted;

  const message =
    `✅ SwiftZone WiFi\n` +
    `Your ${plan.label} voucher code is:\n\n` +
    `🔑 ${voucherCode}\n\n` +
    `Connect to SWIFTZONE_FREE WiFi, then enter this code on the login page.\n` +
    `Valid for: ${plan.label} | Speed: ${plan.speed}\n\n` +
    `Support: wa.me/254700000000`;

  await sms.send({
    to: [formatted],
    message,
    from: process.env.AT_SENDER_ID || 'SwiftZone',
  });

  console.log(`📱 SMS sent to ${formatted}: ${voucherCode}`);
}

// ─────────────────────────────────────────
// NOTIFY OWNER (SMS)
// ─────────────────────────────────────────
async function notifyOwner(phone, bundle, amount, voucherCode) {
  const plan = BUNDLES[bundle];
  const ownerPhone = process.env.OWNER_PHONE;
  if (!ownerPhone) return;

  let formatted = ownerPhone.replace(/\s/g, '');
  if (formatted.startsWith('0')) formatted = '+254' + formatted.slice(1);

  const message =
    `💰 SwiftZone Sale!\n` +
    `Bundle: ${plan.label}\n` +
    `Amount: Ksh ${amount}\n` +
    `Customer: ${phone}\n` +
    `Voucher: ${voucherCode}\n` +
    `Time: ${new Date().toLocaleString('en-KE')}`;

  await sms.send({
    to: [formatted],
    message,
    from: process.env.AT_SENDER_ID || 'SwiftZone',
  });
}

// ─────────────────────────────────────────
// ROUTE 1: INITIATE STK PUSH
// POST /api/pay
// Body: { phone, bundle }
// ─────────────────────────────────────────
app.post('/api/pay', async (req, res) => {
  const { phone, bundle } = req.body;

  if (!phone || !bundle || !BUNDLES[bundle]) {
    return res.status(400).json({ success: false, message: 'Invalid phone or bundle.' });
  }

  const plan = BUNDLES[bundle];

  try {
    const token = await getMpesaToken();

    // Generate timestamp & password
    const shortcode = process.env.MPESA_SHORTCODE;
    const passkey = process.env.MPESA_PASSKEY;
    const timestamp = new Date().toISOString().replace(/[-T:.Z]/g, '').slice(0, 14);
    const password = Buffer.from(`${shortcode}${passkey}${timestamp}`).toString('base64');

    // Format phone
    let formatted = phone.replace(/\s/g, '');
    if (formatted.startsWith('0')) formatted = '254' + formatted.slice(1);
    if (formatted.startsWith('+')) formatted = formatted.slice(1);

    const response = await axios.post(
      'https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest',
      {
        BusinessShortCode: shortcode,
        Password: password,
        Timestamp: timestamp,
        TransactionType: 'CustomerPayBillOnline',
        Amount: plan.price,
        PartyA: formatted,
        PartyB: shortcode,
        PhoneNumber: formatted,
        CallBackURL: `${process.env.SERVER_URL}/api/mpesa-callback`,
        AccountReference: `SwiftZone-${bundle}`,
        TransactionDesc: `SwiftZone ${plan.label} Bundle`,
      },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    // Store pending payment temporarily (use Redis or DB in production)
    pendingPayments[response.data.CheckoutRequestID] = { phone: formatted, bundle };

    res.json({
      success: true,
      message: `M-Pesa prompt sent to ${phone}. Enter your PIN to complete payment.`,
      checkoutRequestID: response.data.CheckoutRequestID,
    });

  } catch (err) {
    console.error('STK Push error:', err.response?.data || err.message);
    res.status(500).json({ success: false, message: 'Payment initiation failed. Try again.' });
  }
});

// ─────────────────────────────────────────
// TEMPORARY STORAGE (use Redis/DB in prod)
// ─────────────────────────────────────────
const pendingPayments = {};

// ─────────────────────────────────────────
// ROUTE 2: MPESA CALLBACK
// POST /api/mpesa-callback
// Called automatically by Safaricom
// ─────────────────────────────────────────
app.post('/api/mpesa-callback', async (req, res) => {
  // Always respond 200 immediately to Safaricom
  res.status(200).json({ ResultCode: 0, ResultDesc: 'Success' });

  try {
    const callback = req.body.Body?.stkCallback;
    if (!callback) return;

    const { ResultCode, CheckoutRequestID, CallbackMetadata } = callback;

    // Payment failed or cancelled
    if (ResultCode !== 0) {
      console.log(`❌ Payment failed: ${callback.ResultDesc}`);
      return;
    }

    // Extract payment details
    const meta = CallbackMetadata?.Item || [];
    const amount   = meta.find(i => i.Name === 'Amount')?.Value;
    const mpesaRef = meta.find(i => i.Name === 'MpesaReceiptNumber')?.Value;
    const phone    = meta.find(i => i.Name === 'PhoneNumber')?.Value?.toString();

    console.log(`✅ Payment received: Ksh ${amount} | Ref: ${mpesaRef} | Phone: ${phone}`);

    // Get pending payment info
    const pending = pendingPayments[CheckoutRequestID];
    if (!pending) {
      console.log('⚠️ No pending payment found for', CheckoutRequestID);
      return;
    }

    const { bundle } = pending;
    delete pendingPayments[CheckoutRequestID];

    // 1. Generate voucher code
    const voucherCode = generateVoucherCode();
    console.log(`🎟 Generated voucher: ${voucherCode} for ${bundle}`);

    // 2. Create voucher on MikroTik router
    await createMikrotikVoucher(bundle, voucherCode);
    console.log(`🔧 MikroTik voucher created: ${voucherCode}`);

    // 3. Send voucher to customer via SMS
    await sendVoucherSMS(phone, voucherCode, bundle);

    // 4. Notify owner
    await notifyOwner(phone, bundle, amount, voucherCode);

    console.log(`🎉 Complete! Voucher ${voucherCode} delivered to ${phone}`);

  } catch (err) {
    console.error('Callback processing error:', err.message);
  }
});

// ─────────────────────────────────────────
// ROUTE 3: CHECK PAYMENT STATUS
// GET /api/status/:checkoutRequestID
// ─────────────────────────────────────────
app.get('/api/status/:id', (req, res) => {
  const pending = pendingPayments[req.params.id];
  res.json({
    status: pending ? 'pending' : 'completed',
  });
});

// ─────────────────────────────────────────
// ROUTE 4: HEALTH CHECK
// ─────────────────────────────────────────
app.get('/health', (req, res) => {
  res.json({ status: 'SwiftZone backend running ✅', time: new Date().toISOString() });
});

// ─────────────────────────────────────────
// START SERVER
// ─────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`\n🚀 SwiftZone backend running on port ${PORT}`);
  console.log(`📡 Callback URL: ${process.env.SERVER_URL}/api/mpesa-callback\n`);
});
